name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: secrets
        run: echo "MY_SECRET_ENV=${{ secrets.MY_SECRET_ENV}}"
      - name: envs
        run: echo "MY_ENV=${{ var.MY_ENV}}"

      
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    steps:
      - name: secrets
        run: echo "MY_SECRET_ENV=${{ secrets.MY_SECRET_ENV}}"
      - name: envs
        run: echo "MY_ENV=${{ var.MY_ENV}}"
