name: Go

on:
  push:
    branches:
      - main
    paths:
      - '*.go'
      - '*.mod'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [1.19.13, 1.20.14]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
