name: Go Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [1.19.13, 1.20.14]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Enable Debug Logging
      run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v -o test-action

    - name: Run tests
      run: go test -v ./...

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://api.github.com/repos/susannamartinelli/action-test/releases
        asset_path: ./test-action
        asset_name: test-action
        asset_content_type: application/octet-stream
